export const data = {

  'Action(set_A)': {
    cry: {
      word: 'cry',
      translation: 'плакать',
      image: 'img/cry.jpg',
      audioSrc: 'audio/cry.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    dance: {
      word: 'dance',
      translation: 'танцевать',
      image: 'img/dance.jpg',
      audioSrc: 'audio/dance.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    dive: {
      word: 'dive',
      translation: 'нырять',
      image: 'img/dive.jpg',
      audioSrc: 'audio/dive.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    draw: {
      word: 'draw',
      translation: 'рисовать',
      image: 'img/draw.jpg',
      audioSrc: 'audio/draw.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    fish: {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'img/fish.jpg',
      audioSrc: 'audio/fish.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    fly: {
      word: 'fly',
      translation: 'летать',
      image: 'img/fly.jpg',
      audioSrc: 'audio/fly.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    hug: {
      word: 'hug',
      translation: 'обнимать',
      image: 'img/hug.jpg',
      audioSrc: 'audio/hug.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    jump: {
      word: 'jump',
      translation: 'прыгать',
      image: 'img/jump.jpg',
      audioSrc: 'audio/jump.mp3',
      category: 'Action(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  'Action(set_B)': {
    open: {
      word: 'open',
      translation: 'открывать',
      image: 'img/open.jpg',
      audioSrc: 'audio/open.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    play: {
      word: 'play',
      translation: 'играть',
      image: 'img/play.jpg',
      audioSrc: 'audio/play.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    point: {
      word: 'point',
      translation: 'указывать',
      image: 'img/point.jpg',
      audioSrc: 'audio/point.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    ride: {
      word: 'ride',
      translation: 'ездить',
      image: 'img/ride.jpg',
      audioSrc: 'audio/ride.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    run: {
      word: 'run',
      translation: 'бегать',
      image: 'img/run.jpg',
      audioSrc: 'audio/run.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    sing: {
      word: 'sing',
      translation: 'петь',
      image: 'img/sing.jpg',
      audioSrc: 'audio/sing.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    skip: {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'img/skip.jpg',
      audioSrc: 'audio/skip.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    swim: {
      word: 'swim',
      translation: 'плавать',
      image: 'img/swim.jpg',
      audioSrc: 'audio/swim.mp3',
      category: 'Action(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  'Animal(set_A)': {
    cat: {
      word: 'cat',
      translation: 'кот',
      image: 'img/cat.jpg',
      audioSrc: 'audio/cat.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    chick: {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'img/chick.jpg',
      audioSrc: 'audio/chick.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    chicken: {
      word: 'chicken',
      translation: 'курица',
      image: 'img/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    dog: {
      word: 'dog',
      translation: 'собака',
      image: 'img/dog.jpg',
      audioSrc: 'audio/dog.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    horse: {
      word: 'horse',
      translation: 'лошадь',
      image: 'img/horse.jpg',
      audioSrc: 'audio/horse.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    pig: {
      word: 'pig',
      translation: 'свинья',
      image: 'img/pig.jpg',
      audioSrc: 'audio/pig.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    rabbit: {
      word: 'rabbit',
      translation: 'кролик',
      image: 'img/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
    sheep: {
      word: 'sheep',
      translation: 'овца',
      image: 'img/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
      category: 'Animal(set_A)',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  'Animal(set_B)': {
    bird: {
      word: 'bird',
      translation: 'птица',
      image: 'img/bird.jpg',
      audioSrc: 'audio/bird.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    fish: {
      word: 'fish',
      translation: 'рыба',
      image: 'img/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    frog: {
      word: 'frog',
      translation: 'жаба',
      image: 'img/frog.jpg',
      audioSrc: 'audio/frog.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    giraffe: {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'img/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    lion: {
      word: 'lion',
      translation: 'лев',
      image: 'img/lion.jpg',
      audioSrc: 'audio/lion.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    mouse: {
      word: 'mouse',
      translation: 'мышь',
      image: 'img/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    turtle: {
      word: 'turtle',
      translation: 'черепаха',
      image: 'img/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
    dolphin: {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'img/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
      category: 'Animal(set_B)',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  Clothes: {
    skirt: {
      word: 'skirt',
      translation: 'юбка',
      image: 'img/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    pants: {
      word: 'pants',
      translation: 'брюки',
      image: 'img/pants.jpg',
      audioSrc: 'audio/pants.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    blouse: {
      word: 'blouse',
      translation: 'блузка',
      image: 'img/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    dress: {
      word: 'dress',
      translation: 'платье',
      image: 'img/dress.jpg',
      audioSrc: 'audio/dress.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    boot: {
      word: 'boot',
      translation: 'ботинок',
      image: 'img/boot.jpg',
      audioSrc: 'audio/boot.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    shirt: {
      word: 'shirt',
      translation: 'рубашка',
      image: 'img/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    coat: {
      word: 'coat',
      translation: 'пальто',
      image: 'img/coat.jpg',
      audioSrc: 'audio/coat.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
    shoe: {
      word: 'shoe',
      translation: 'туфли',
      image: 'img/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
      category: 'Clothes',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  Emotions: {
    sad: {
      word: 'sad',
      translation: 'грустный',
      image: 'img/sad.jpg',
      audioSrc: 'audio/sad.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    angry: {
      word: 'angry',
      translation: 'сердитый',
      image: 'img/angry.jpg',
      audioSrc: 'audio/angry.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    happy: {
      word: 'happy',
      translation: 'счастливый',
      image: 'img/happy.jpg',
      audioSrc: 'audio/happy.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    tired: {
      word: 'tired',
      translation: 'уставший',
      image: 'img/tired.jpg',
      audioSrc: 'audio/tired.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    surprised: {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'img/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    scared: {
      word: 'scared',
      translation: 'испуганный',
      image: 'img/scared.jpg',
      audioSrc: 'audio/scared.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    smile: {
      word: 'smile',
      translation: 'улыбка',
      image: 'img/smile.jpg',
      audioSrc: 'audio/smile.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
    laugh: {
      word: 'laugh',
      translation: 'смех',
      image: 'img/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
      category: 'Emotions',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  Foods: {
    bread: {
      word: 'bread',
      translation: 'хлеб',
      image: 'img/bread.jpg',
      audioSrc: 'audio/bread.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    cheese: {
      word: 'cheese',
      translation: 'сыр',
      image: 'img/cheese.jpg',
      audioSrc: 'audio/cheese.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    coffee: {
      word: 'coffee',
      translation: 'кофе',
      image: 'img/coffee.jpg',
      audioSrc: 'audio/coffee.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    honey: {
      word: 'honey',
      translation: 'мёд',
      image: 'img/honey.jpg',
      audioSrc: 'audio/honey.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    jam: {
      word: 'jam',
      translation: 'варенье',
      image: 'img/jam.jpg',
      audioSrc: 'audio/jam.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    meat: {
      word: 'meat',
      translation: 'мясо',
      image: 'img/meat.jpg',
      audioSrc: 'audio/meat.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    rice: {
      word: 'rice',
      translation: 'рис',
      image: 'img/rice.jpg',
      audioSrc: 'audio/rice.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
    soup: {
      word: 'soup',
      translation: 'суп',
      image: 'img/soup.jpg',
      audioSrc: 'audio/soup.mp3',
      category: 'Foods',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
  Seasons: {
    cold: {
      word: 'cold',
      translation: 'холодно',
      image: 'img/cold.jpg',
      audioSrc: 'audio/cold.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    day: {
      word: 'day',
      translation: 'день',
      image: 'img/day.jpg',
      audioSrc: 'audio/day.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    fall: {
      word: 'fall',
      translation: 'осень',
      image: 'img/falling.jpg',
      audioSrc: 'audio/fall.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    hot: {
      word: 'hot',
      translation: 'тепло',
      image: 'img/hot.jpg',
      audioSrc: 'audio/hot.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    moon: {
      word: 'moon',
      translation: 'луна',
      image: 'img/moon.jpg',
      audioSrc: 'audio/moon.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    spring: {
      word: 'spring',
      translation: 'весна',
      image: 'img/spring.jpg',
      audioSrc: 'audio/spring.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    summer: {
      word: 'summer',
      translation: 'лето',
      image: 'img/summer.jpg',
      audioSrc: 'audio/summer.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
    winter: {
      word: 'winter',
      translation: 'зима',
      image: 'img/winter.jpg',
      audioSrc: 'audio/winter.mp3',
      category: 'Seasons',
      train: 0,
      correct: 0,
      error: 0,
    },
  },
};
